/* EveOS Manifest Scripts Part */
window.EveModuleManifestParts = window.EveModuleManifestParts || {};
window.EveModuleManifestScriptChunks = window.EveModuleManifestScriptChunks || [];

window.EveModuleManifestScriptChunks.push([
    // UI Modules
    "js/modules/ui/notifications/templates.js?v=0.1.1",
    "js/modules/ui/notifications/toast.js?v=0.1.1",
    "js/modules/ui/notifications/dialogs.js?v=0.1.1",
    "js/modules/features/data-state/data-state.capture.clone.js?v=0.2.2",
    "js/modules/features/data-state/data-state.capture.scoped.js?v=0.2.2",
    "js/modules/features/data-state/data-state.capture.js?v=0.2.2",
    "js/modules/features/data-state/data-state.apply.shared.js?v=0.2.2",
    "js/modules/features/data-state/data-state.apply.scoped.js?v=0.2.3",
    "js/modules/features/data-state/data-state.apply.js?v=0.2.1",
    "js/modules/features/data-state/data-state.core.js",
    "js/modules/features/data-transfer/data-transfer.shared.js?v=0.2.1",
    "js/modules/features/data-transfer/data-transfer.export.naming.js?v=0.2.1",
    "js/modules/features/data-transfer/data-transfer.export.library.js",
    "js/modules/features/data-transfer/data-transfer.export.utils.js",
    "js/modules/features/data-transfer/data-transfer.export.folder.writer.js?v=0.2.3",
    "js/modules/features/data-transfer/data-transfer.export.folder.backups.js?v=0.2.2",
    "js/modules/features/data-transfer/data-transfer.export.folder.paths.js",
    "js/modules/features/data-transfer/data-transfer.export.folder.js?v=0.2.1",
    "js/modules/features/data-transfer/data-transfer.export.js?v=0.2.2",
    "js/modules/features/data-transfer/data-transfer.folder-import.fs.js?v=0.2.1",
    "js/modules/features/data-transfer/data-transfer.folder-import.state.infer.js?v=0.2.1",
    "js/modules/features/data-transfer/data-transfer.folder-import.state.build.js?v=0.2.4",
    "js/modules/features/data-transfer/data-transfer.folder-import.state.js?v=0.2.1",
    "js/modules/features/data-transfer/data-transfer.folder-import.parse.handles.js?v=0.2.4",
    "js/modules/features/data-transfer/data-transfer.folder-import.parse.root.js?v=0.2.3",
    "js/modules/features/data-transfer/data-transfer.folder-import.parse.js?v=0.2.1",
    "js/modules/features/data-transfer/data-transfer.folder-import.activate.js?v=0.2.2",
    "js/modules/features/data-transfer/data-transfer.folder-import.restore.js?v=0.2.4",
    "js/modules/features/data-transfer/data-transfer.folder-import.js?v=0.2.1",
    "js/modules/features/data-transfer/data-transfer.import-actions.js?v=0.2.1",
    "js/modules/features/data-transfer/data-transfer.core.js",
    "js/modules/features/duplicate-sensor.base.js?v=0.1.0",
    "js/modules/features/duplicate-sensor.scan.js?v=0.1.0",
    "js/modules/features/duplicate-sensor.merge.js?v=0.1.0",
    "js/modules/features/duplicate-sensor.js?v=0.2.0",
    "js/modules/features/modular-state-sync/modular-state-sync.shared.js?v=0.3.0",
    "js/modules/features/modular-state-sync/modular-state-sync.engine.sync.js?v=0.3.1",
    "js/modules/features/modular-state-sync/modular-state-sync.engine.runtime.js?v=0.3.1",
    "js/modules/features/modular-state-sync/modular-state-sync.engine.js?v=0.3.1",
    "js/modules/features/modular-state-sync/modular-state-sync.api.context.js?v=0.3.1",
    "js/modules/features/modular-state-sync/modular-state-sync.api.store.js?v=0.3.2",
    "js/modules/features/modular-state-sync/modular-state-sync.api.js?v=0.3.1",
    "js/modules/features/modular-state-sync/modular-state-sync.core.js?v=0.3.0",
    "js/modules/ui/visuals.js?v=0.2.39",
    "js/modules/ui/header.js",
    "js/modules/features/header-controls/hc-state.js",
    "js/modules/features/header-controls/hc-ui.form.js",
    "js/modules/features/header-controls/hc-ui.js",
    "js/modules/ui/sidebar.js?v=0.2.38",
    "js/modules/ui/dashboard/dashboard-dock.js?v=0.2.4"
]);
