window.EveConstellationMap = window.EveConstellationMap || {};

(function (ns) {
    const shared = ns._shared || {};
    const {
        state,
        FX_TUNING_FIELDS,
        MOTION_TUNING_FIELDS,
        AURA_TUNING_FIELDS,
        AURA_PRESETS,
        AURA_DEPTH_ORDER,
        escapeHtml,
        getMotionTuningText,
        getFxTuningText,
        getAuraTuningText,
        getAuraPresetText,
        getKindDisplayName
    } = shared;

    function getInteractionTargetNode() {
        return state.selected || state.hovered || null;
    }

    function buildRangeNumberRows(fields, rangeAttr, numberAttr, valueAttr) {
        return fields.map((field) => [
            '<label class="map-controls-range-row">',
            '<span>' + escapeHtml(field.label) + '</span>',
            '<input ' + rangeAttr + '="' + escapeHtml(field.key) + '" type="range" min="' + escapeHtml(String(field.min)) + '" max="' + escapeHtml(String(field.max)) + '" step="' + escapeHtml(String(field.step)) + '" value="' + escapeHtml(rangeAttr.indexOf('motion') !== -1 ? getMotionTuningText(field.key) : getAuraTuningText(field.key)) + '">',
            '<span ' + valueAttr + '="' + escapeHtml(field.key) + '" class="map-controls-range-value">' + escapeHtml(rangeAttr.indexOf('motion') !== -1 ? getMotionTuningText(field.key) : getAuraTuningText(field.key)) + '</span>',
            '<input ' + numberAttr + '="' + escapeHtml(field.key) + '" type="number" min="' + escapeHtml(String(field.min)) + '" max="' + escapeHtml(String(field.max)) + '" step="' + escapeHtml(String(field.step)) + '" value="' + escapeHtml(rangeAttr.indexOf('motion') !== -1 ? getMotionTuningText(field.key) : getAuraTuningText(field.key)) + '" class="map-controls-number-input">',
            '</label>'
        ].join('')).join('');
    }

    function buildAuraTuningMarkup(section) {
        const fields = AURA_TUNING_FIELDS.filter((field) => field.section === section);
        return buildRangeNumberRows(fields, 'data-map-aura-tuning', 'data-map-aura-tuning-number', 'data-map-aura-tuning-value');
    }

    function buildFxTuningMarkup(section) {
        const fields = FX_TUNING_FIELDS.filter((field) => field.section === section);
        return fields.map((field) => [
            '<label class="map-controls-range-row">',
            '<span>' + escapeHtml(field.label) + '</span>',
            '<input data-map-fx-tuning="' + escapeHtml(field.key) + '" type="range" min="' + escapeHtml(String(field.min)) + '" max="' + escapeHtml(String(field.max)) + '" step="' + escapeHtml(String(field.step)) + '" value="' + escapeHtml(getFxTuningText(field.key)) + '">',
            '<span data-map-fx-tuning-value="' + escapeHtml(field.key) + '" class="map-controls-range-value">' + escapeHtml(getFxTuningText(field.key)) + '</span>',
            '<input data-map-fx-tuning-number="' + escapeHtml(field.key) + '" type="number" min="' + escapeHtml(String(field.min)) + '" max="' + escapeHtml(String(field.max)) + '" step="' + escapeHtml(String(field.step)) + '" value="' + escapeHtml(getFxTuningText(field.key)) + '" class="map-controls-number-input">',
            '</label>'
        ].join('')).join('');
    }

    function buildMotionTuningMarkup() {
        return buildRangeNumberRows(MOTION_TUNING_FIELDS, 'data-map-motion-tuning', 'data-map-motion-tuning-number', 'data-map-motion-tuning-value');
    }

    function buildPresetButtons() {
        return Object.entries(AURA_PRESETS).map(([key, preset]) => {
            return '<button type="button" data-map-aura-preset="' + escapeHtml(key) + '" class="map-btn">' + escapeHtml(preset.label) + '</button>';
        }).join('');
    }

    function buildDepthButtons() {
        const labels = {
            root: 'Root Layer',
            layer1: 'Layer 1',
            layer2: 'Layer 2',
            layer3plus: 'Layer 3+'
        };
        return AURA_DEPTH_ORDER.map((key) => {
            return '<button type="button" data-map-aura-depth="' + escapeHtml(key) + '" class="map-btn">' + escapeHtml(labels[key] || key) + '</button>';
        }).join('');
    }

    function buildOverlayMarkup() {
        return [
            '<style>',
            '.map-controls-panel{display:none;flex-direction:column;gap:12px;align-items:stretch;align-self:stretch;box-sizing:border-box;width:min(100%,1080px);min-width:0;max-width:100%;max-height:min(calc(100vh - 112px),820px);min-height:0;padding:14px 16px;border:1px solid rgba(255,255,255,0.14);background:linear-gradient(180deg,rgba(7,16,30,0.96) 0%,rgba(4,10,20,0.92) 100%);border-radius:16px;box-shadow:0 18px 34px rgba(0,0,0,0.28);backdrop-filter:blur(12px);overflow:hidden;}',
            '.map-controls-scroll{display:flex;flex:1 1 auto;min-height:0;flex-direction:column;gap:12px;overflow-y:auto;overflow-x:hidden;padding-right:8px;scrollbar-width:thin;scrollbar-color:rgba(96,218,255,0.62) rgba(255,255,255,0.08);}',
            '.map-controls-scroll::-webkit-scrollbar{width:10px;}',
            '.map-controls-scroll::-webkit-scrollbar-track{background:rgba(255,255,255,0.07);border-radius:999px;}',
            '.map-controls-scroll::-webkit-scrollbar-thumb{background:linear-gradient(180deg,rgba(84,205,255,0.95) 0%,rgba(34,129,210,0.95) 100%);border-radius:999px;border:2px solid rgba(3,10,20,0.86);}',
            '.map-controls-scroll::-webkit-scrollbar-thumb:hover{background:linear-gradient(180deg,rgba(112,222,255,1) 0%,rgba(49,154,235,1) 100%);}',
            '.map-controls-scroll > *{min-width:0;}',
            '.map-controls-section{box-sizing:border-box;min-width:0;border:1px solid rgba(255,255,255,0.08);background:rgba(255,255,255,0.03);border-radius:14px;padding:10px 12px;}',
            '.map-controls-section summary{list-style:none;}',
            '.map-controls-section summary::-webkit-details-marker{display:none;}',
            '.map-controls-section[open] summary{margin-bottom:2px;}',
            '.map-controls-grid{display:grid;gap:14px 18px;align-items:start;min-width:0;}',
            '.map-controls-grid-2{grid-template-columns:repeat(auto-fit,minmax(260px,1fr));}',
            '.map-controls-grid-3{grid-template-columns:repeat(auto-fit,minmax(220px,1fr));}',
            '.map-controls-stack{display:flex;flex-direction:column;gap:8px;min-width:0;}',
            '.map-controls-chip-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap;min-width:0;}',
            '.map-controls-summary{font-size:0.74rem;color:rgba(255,255,255,0.72);padding-left:4px;min-width:0;overflow-wrap:anywhere;}',
            '.map-controls-range-row{display:grid;grid-template-columns:minmax(92px,120px) minmax(0,1fr) 46px 64px;align-items:center;gap:8px;font-size:0.74rem;color:rgba(255,255,255,0.82);min-width:0;}',
            '.map-controls-range-row > span:first-child{min-width:0;overflow-wrap:anywhere;}',
            '.map-controls-range-row input[type="range"]{width:100%;min-width:0;}',
            '.map-controls-range-value{min-width:0;text-align:right;}',
            '.map-controls-number-input{width:64px;box-sizing:border-box;border:1px solid rgba(255,255,255,0.16);background:rgba(255,255,255,0.07);color:#fff;border-radius:8px;padding:6px 8px;outline:none;}',
            '.map-action-wheel{position:absolute;z-index:4;inset:0;display:none;pointer-events:none;}',
            '.map-action-wheel.is-visible{display:block;}',
            '.map-action-wheel-center{position:absolute;width:92px;height:92px;display:flex;align-items:center;justify-content:center;padding:12px;border-radius:999px;border:1px solid rgba(255,255,255,0.16);background:radial-gradient(circle at 32% 24%, rgba(18,36,62,0.96), rgba(4,10,20,0.96));box-shadow:0 18px 40px rgba(0,0,0,0.34);transform:translate(-50%,-50%);text-align:center;color:#f4fbff;font-size:0.72rem;font-weight:700;letter-spacing:0.03em;pointer-events:auto;}',
            '.map-action-wheel-item{position:absolute;display:inline-flex;align-items:center;justify-content:center;min-width:96px;max-width:132px;padding:9px 12px;border-radius:999px;border:1px solid rgba(255,255,255,0.18);background:rgba(6,18,34,0.94);color:#f6fbff;font-size:0.72rem;font-weight:600;line-height:1.2;box-shadow:0 14px 28px rgba(0,0,0,0.26);transform:translate(-50%,-50%);pointer-events:auto;cursor:pointer;text-align:center;}',
            '.map-action-wheel-item.is-accent{border-color:rgba(0,212,255,0.34);background:rgba(0,212,255,0.14);}',
            '.map-action-wheel-item:hover{border-color:rgba(145,220,255,0.44);background:rgba(145,220,255,0.18);}',
            '@media (max-width: 1100px){.map-controls-range-row{grid-template-columns:minmax(82px,108px) minmax(0,1fr) 42px 58px;gap:6px;}.map-controls-number-input{width:58px;padding:6px;}}',
            '@media (max-width: 820px){.map-controls-grid-2,.map-controls-grid-3{grid-template-columns:minmax(0,1fr);}.map-controls-panel{padding:12px;max-height:min(calc(100vh - 124px),820px);}.map-controls-summary{padding-left:0;}}',
            '</style>',
            '<div class="map-css-layer map-css-grid-layer"></div>',
            '<div class="map-css-layer map-css-tech-layer"></div>',
            '<div class="map-css-layer map-css-circuit-layer"></div>',
            '<div class="map-css-layer map-css-scanline-layer"></div>',
            '<div style="position:absolute;z-index:3;top:16px;left:20px;display:flex;flex-direction:column;gap:4px;max-width:min(48vw,680px);pointer-events:auto;">',
            '<div data-map-title style="font-size:1.05rem;font-weight:700;letter-spacing:0.06em;color:#f3f8ff;">NEURAL CORE :: CONSTELLATION MAP</div>',
            '<div data-map-scope style="font-size:0.82rem;color:rgba(255,255,255,0.76);"></div>',
            '<div data-map-stats style="font-size:0.78rem;color:rgba(255,255,255,0.58);"></div>',
            '</div>',
            '<div style="position:absolute;z-index:3;top:16px;right:20px;display:flex;flex-direction:column;gap:8px;align-items:flex-end;width:min(calc(100vw - 40px),980px);max-width:calc(100vw - 40px);pointer-events:auto;">',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;justify-content:flex-end;">',
            '<input data-map-find type="search" placeholder="Find bookmark, card, folder..." style="min-width:240px;border:1px solid rgba(255,255,255,0.18);background:rgba(255,255,255,0.07);color:#fff;border-radius:10px;padding:8px 12px;outline:none;">',
            '<button type="button" data-map-toolbar="find" class="map-btn">Find</button>',
            '<button type="button" data-map-toolbar="zoom-out" class="map-btn">-</button>',
            '<button type="button" data-map-toolbar="zoom-in" class="map-btn">+</button>',
            '<button type="button" data-map-toolbar="fit" class="map-btn">Fit</button>',
            '<button type="button" data-map-toolbar="reset" class="map-btn">Reset</button>',
            '<button type="button" data-map-toolbar="labels" class="map-btn">Labels: Auto</button>',
            '<button type="button" data-map-toolbar="motion" class="map-btn">Motion: Web</button>',
            '<button type="button" data-map-toolbar="controls" class="map-btn">Control Center</button>',
            '<button type="button" data-map-toolbar="close" class="map-btn" style="border-color:rgba(255,80,120,0.3);background:rgba(255,80,120,0.14);">Close</button>',
            '</div>',
            '<div data-map-controls-panel class="map-controls-panel">',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;justify-content:space-between;">',
            '<div style="font-size:0.86rem;font-weight:700;letter-spacing:0.04em;color:#f3f8ff;">Constellation Control Center</div>',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;justify-content:flex-end;">',
            '<button type="button" data-map-toolbar="aura-reset" class="map-btn">Reset Auras</button>',
            '<button type="button" data-map-toolbar="motion-reset" class="map-btn">Reset Motion</button>',
            '<button type="button" data-map-toolbar="controls-reset" class="map-btn">Reset All</button>',
            '</div>',
            '</div>',
            '<div class="map-controls-scroll">',
            '<details open class="map-controls-section">',
            '<summary style="cursor:pointer;font-size:0.82rem;font-weight:700;color:#f7fbff;">Background FX</summary>',
            '<div data-map-fx-panel style="display:flex;flex-direction:column;gap:10px;padding-top:10px;">',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;justify-content:space-between;">',
            '<div style="font-size:0.74rem;color:rgba(255,255,255,0.72);">Interactive background engine, visual stack, and responsive tuning.</div>',
            '<button type="button" data-map-toolbar="fx-reset" class="map-btn">Reset FX</button>',
            '</div>',
            '<div class="fx-row">',
            '<div class="fx-label">Background Engine</div>',
            '<div class="fx-grid">',
            '<button class="fx-item-btn" data-fx-engine="none">None</button>',
            '<button class="fx-item-btn" data-fx-engine="solaris">Solaris</button>',
            '<button class="fx-item-btn" data-fx-engine="neural">Neural</button>',
            '<button class="fx-item-btn" data-fx-engine="waves">Waves</button>',
            '<button class="fx-item-btn" data-fx-engine="tokamak">Tokamak</button>',
            '<button class="fx-item-btn" data-fx-engine="memento">Memento</button>',
            '<button class="fx-item-btn" data-fx-engine="art">Art</button>',
            '<button class="fx-item-btn" data-fx-engine="raymarching">Raymarch</button>',
            '<button class="fx-item-btn" data-fx-engine="attraction">Attract</button>',
            '<button class="fx-item-btn" data-fx-engine="ascii">ASCII</button>',
            '<button class="fx-item-btn" data-fx-engine="blurred">Blurred</button>',
            '<button class="fx-item-btn" data-fx-engine="svgfilters">SVG Filter</button>',
            '<button class="fx-item-btn" data-fx-engine="particles">Particles</button>',
            '<button class="fx-item-btn" data-fx-engine="shaderedit">Shader Edit</button>',
            '<button class="fx-item-btn" data-fx-engine="dotwave">Dot Wave</button>',
            '<button class="fx-item-btn" data-fx-engine="cosmicsun">Cosmic Sun</button>',
            '<button class="fx-item-btn" data-fx-engine="auracursor">Aura Cursor</button>',
            '</div>',
            '</div>',
            '<div class="fx-row">',
            '<div class="fx-label">Visual Layers</div>',
            '<div class="fx-toggle-group">',
            '<div class="fx-toggle-chip" data-fx-toggle="grid">Grid</div>',
            '<div class="fx-toggle-chip" data-fx-toggle="scanline">Scanline</div>',
            '<div class="fx-toggle-chip" data-fx-toggle="tech">Tech</div>',
            '<div class="fx-toggle-chip" data-fx-toggle="circuit">Circuit</div>',
            '<div class="fx-toggle-chip" data-fx-toggle="neuralhud">Neural HUD</div>',
            '</div>',
            '</div>',
            '<div class="fx-row">',
            '<div class="fx-label">Interactive Controls</div>',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;">',
            '<button type="button" data-map-fx-flag="pointerReactive" class="map-btn">Pointer Reactive</button>',
            '<button type="button" data-map-fx-flag="parallaxEnabled" class="map-btn">Camera Parallax</button>',
            '</div>',
            '</div>',
            '<div class="map-controls-grid map-controls-grid-2">',
            '<div class="map-controls-stack">',
            '<div style="font-size:0.76rem;font-weight:700;color:rgba(255,255,255,0.82);">Engine Dynamics</div>',
            buildFxTuningMarkup('engine'),
            '</div>',
            '<div class="map-controls-stack">',
            '<div style="font-size:0.76rem;font-weight:700;color:rgba(255,255,255,0.82);">Layer Stack</div>',
            buildFxTuningMarkup('layers'),
            '<div style="font-size:0.76rem;font-weight:700;color:rgba(255,255,255,0.82);padding-top:4px;">ASCII Layout</div>',
            buildFxTuningMarkup('ascii'),
            '</div>',
            '</div>',
            '</div>',
            '</details>',
            '<details open class="map-controls-section">',
            '<summary style="cursor:pointer;font-size:0.82rem;font-weight:700;color:#f7fbff;">Auras</summary>',
            '<div style="display:flex;flex-direction:column;gap:10px;padding-top:10px;">',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;">',
            '<button type="button" data-map-aura-toggle="visuals" class="map-btn">Aura Volumes: ON</button>',
            '<button type="button" data-map-aura-toggle="effects" class="map-btn">Aura Forces: ON</button>',
            '<button type="button" data-map-aura-emitter="workspace" class="map-btn">Tab Auras</button>',
            '<button type="button" data-map-aura-emitter="category" class="map-btn">Card Auras</button>',
            '<button type="button" data-map-aura-emitter="folder" class="map-btn">Folder Auras</button>',
            '<span data-map-aura-preset-summary class="map-controls-summary">' + escapeHtml(getAuraPresetText()) + '</span>',
            '</div>',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;">',
            buildDepthButtons(),
            '</div>',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;">',
            buildPresetButtons(),
            '</div>',
            '<div class="map-controls-grid map-controls-grid-3">',
            '<div class="map-controls-stack">',
            '<div style="font-size:0.76rem;font-weight:700;color:rgba(255,255,255,0.82);">Tab Shape</div>',
            buildAuraTuningMarkup('workspace'),
            '</div>',
            '<div class="map-controls-stack">',
            '<div style="font-size:0.76rem;font-weight:700;color:rgba(255,255,255,0.82);">Card Shape</div>',
            buildAuraTuningMarkup('card'),
            '</div>',
            '<div class="map-controls-stack">',
            '<div style="font-size:0.76rem;font-weight:700;color:rgba(255,255,255,0.82);">Folder Shape</div>',
            buildAuraTuningMarkup('folder'),
            '</div>',
            '</div>',
            '</div>',
            '</details>',
            '<details open class="map-controls-section">',
            '<summary style="cursor:pointer;font-size:0.82rem;font-weight:700;color:#f7fbff;">Motion</summary>',
            '<div style="display:flex;flex-direction:column;gap:10px;padding-top:10px;">',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;">',
            '<button type="button" data-map-toolbar="motion" class="map-btn">Motion: Web</button>',
            '<button type="button" data-map-toolbar="stability" class="map-btn">Hold Main Nodes: ON</button>',
            '</div>',
            '<div style="display:flex;flex-direction:column;gap:8px;">',
            buildMotionTuningMarkup(),
            '</div>',
            '</div>',
            '</details>',
            '<details open class="map-controls-section">',
            '<summary style="cursor:pointer;font-size:0.82rem;font-weight:700;color:#f7fbff;">Structure</summary>',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;padding-top:10px;">',
            '<button type="button" data-map-toolbar="chain-internal" class="map-btn">Same-Chain Forces: ON</button>',
            '<button type="button" data-map-toolbar="chain-external" class="map-btn">Cross-Chain Forces: ON</button>',
            '<button type="button" data-map-toolbar="chain-hierarchy" class="map-btn">Enforce Folder Layers: ON</button>',
            '<button type="button" data-map-toolbar="bookmark-hierarchy" class="map-btn">Keep Bookmark Lanes: ON</button>',
            '</div>',
            '</details>',
            '<details open class="map-controls-section">',
            '<summary style="cursor:pointer;font-size:0.82rem;font-weight:700;color:#f7fbff;">Chain Editing</summary>',
            '<div style="display:flex;flex-direction:column;gap:10px;padding-top:10px;">',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;">',
            '<button type="button" data-map-toolbar="rewire-mode" class="map-btn">Chain Surgery: OFF</button>',
            '<button type="button" data-map-toolbar="rewire-cancel" class="map-btn">Cancel Move</button>',
            '</div>',
            '<div data-map-rewire-summary class="map-controls-summary">Drag or click a bookmark or folder to arm it, then drop or click a card or folder target. Use Detach to Parking when you want a floating orphan chain.</div>',
            '<div style="font-size:0.76rem;line-height:1.55;color:rgba(255,255,255,0.72);">',
            'Drag bookmark and folder nodes onto card or folder nodes to reattach them, or arm a node and click a valid target for fast reassignment. Right-click nodes for the action wheel, explicit parking detach, and create-and-attach flows. Use workspace or Unidex scope when you want to transfer chains across cards.',
            '</div>',
            '</div>',
            '</details>',
            '<details open class="map-controls-section">',
            '<summary style="cursor:pointer;font-size:0.82rem;font-weight:700;color:#f7fbff;">Static and Flow</summary>',
            '<div style="display:flex;flex-direction:column;gap:10px;padding-top:10px;">',
            '<div class="map-controls-chip-row" style="justify-content:flex-start;">',
            '<button type="button" data-map-toolbar="static-node" class="map-btn">Static Node</button>',
            '<button type="button" data-map-toolbar="static-chain" class="map-btn">Static Chain</button>',
            '<button type="button" data-map-toolbar="static-kind" class="map-btn">Static Type</button>',
            '<button type="button" data-map-toolbar="static-clear" class="map-btn">Clear Static</button>',
            '<div data-map-static-summary class="map-controls-summary">Static: none</div>',
            '</div>',
            '<div class="map-controls-chip-row" style="justify-content:flex-start;">',
            '<button type="button" data-map-static-kind="workspace" class="map-btn">Freeze ' + escapeHtml(getKindDisplayName('workspace')) + '</button>',
            '<button type="button" data-map-static-kind="category" class="map-btn">Freeze ' + escapeHtml(getKindDisplayName('category')) + '</button>',
            '<button type="button" data-map-static-kind="folder" class="map-btn">Freeze ' + escapeHtml(getKindDisplayName('folder')) + '</button>',
            '<button type="button" data-map-static-kind="link" class="map-btn">Freeze ' + escapeHtml(getKindDisplayName('link')) + '</button>',
            '</div>',
            '<div class="map-controls-chip-row" style="justify-content:flex-start;">',
            '<button type="button" data-map-toolbar="polarity-node" class="map-btn">Node: Inherit</button>',
            '<button type="button" data-map-toolbar="polarity-kind" class="map-btn">Type: Push</button>',
            '<button type="button" data-map-toolbar="polarity-clear" class="map-btn">Clear Flow</button>',
            '<div data-map-polarity-summary class="map-controls-summary">Flow: push default</div>',
            '</div>',
            '<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px 16px;align-items:start;">',
            '<label style="display:grid;grid-template-columns:42px minmax(112px,1fr) 50px 64px;align-items:center;gap:8px;font-size:0.74rem;color:rgba(255,255,255,0.82);">',
            '<span>Push</span>',
            '<input data-map-polarity-strength="repel" type="range" min="0" max="2.5" step="0.01" value="0.76" style="width:100%;">',
            '<span data-map-polarity-strength-value="repel" style="min-width:42px;text-align:right;">0.76</span>',
            '<input data-map-polarity-strength-number="repel" type="number" min="0" max="2.5" step="0.01" value="0.76" style="width:64px;border:1px solid rgba(255,255,255,0.16);background:rgba(255,255,255,0.07);color:#fff;border-radius:8px;padding:6px 8px;outline:none;">',
            '</label>',
            '<label style="display:grid;grid-template-columns:42px minmax(112px,1fr) 50px 64px;align-items:center;gap:8px;font-size:0.74rem;color:rgba(255,255,255,0.82);">',
            '<span>Pull</span>',
            '<input data-map-polarity-strength="attract" type="range" min="0" max="2.5" step="0.01" value="0.62" style="width:100%;">',
            '<span data-map-polarity-strength-value="attract" style="min-width:42px;text-align:right;">0.62</span>',
            '<input data-map-polarity-strength-number="attract" type="number" min="0" max="2.5" step="0.01" value="0.62" style="width:64px;border:1px solid rgba(255,255,255,0.16);background:rgba(255,255,255,0.07);color:#fff;border-radius:8px;padding:6px 8px;outline:none;">',
            '</label>',
            '</div>',
            '</div>',
            '</details>',
            '<details class="map-controls-section">',
            '<summary style="cursor:pointer;font-size:0.82rem;font-weight:700;color:#f7fbff;">Help</summary>',
            '<div style="font-size:0.78rem;line-height:1.55;color:rgba(255,255,255,0.74);padding-top:10px;">',
            'Drag background to pan. Hold Space to force-pan through dense clusters. Drag nodes to reorganize. Mouse wheel zooms. Double-click a bookmark node to open it. Turn on Chain Surgery to drag bookmark and folder nodes onto cards or folders, or arm a node and click a valid target for fast reassignment. Right-click nodes for the action wheel, explicit parking detach, and create-and-attach flows. Use Auras to control volumes and chain shaping, Motion to tune physics, and Structure to clamp layer rules.',
            '</div>',
            '</details>',
            '</div>',
            '</div>',
            '</div>',
            '<canvas data-map-canvas style="position:absolute;z-index:1;inset:0;width:100%;height:100%;display:block;cursor:grab;"></canvas>',
            '<div data-map-action-wheel class="map-action-wheel"></div>',
            '<div data-map-info style="position:absolute;z-index:3;right:108px;bottom:20px;max-width:min(360px,calc(100vw - 200px));min-width:260px;border:1px solid rgba(255,255,255,0.14);background:rgba(3,10,20,0.86);border-radius:16px;padding:14px 16px;color:#fff;box-shadow:0 18px 40px rgba(0,0,0,0.35);pointer-events:auto;"></div>'
        ].join('');
    }

    const toolbarMarkup = ns._toolbarMarkup = ns._toolbarMarkup || {};
    Object.assign(toolbarMarkup, {
        getInteractionTargetNode,
        buildMotionTuningMarkup,
        buildOverlayMarkup
    });
})(window.EveConstellationMap);
