window.EveConstellationMap = window.EveConstellationMap || {};

(function (ns) {
    const shared = ns._shared || {};
    const {
        state,
        FX_TUNING_FIELDS,
        MOTION_TUNING_FIELDS,
        AURA_TUNING_FIELDS,
        AURA_PRESETS,
        AURA_DEPTH_ORDER,
        MAP_THEME_COLOR_FIELDS,
        MAP_THEME_TUNING_FIELDS,
        escapeHtml,
        getMotionTuningText,
        getFxTuningText,
        getAuraTuningText,
        getAuraPresetText,
        getMapThemeTuningText,
        getMapThemeSummaryText,
        getMapThemeColorValue,
        getKindDisplayName
    } = shared;

    function getInteractionTargetNode() {
        return state.selected || state.hovered || null;
    }

    function buildRangeNumberRows(fields, rangeAttr, numberAttr, valueAttr) {
        return fields.map((field) => [
            '<label class="map-controls-range-row">',
            '<span>' + escapeHtml(field.label) + '</span>',
            '<input ' + rangeAttr + '="' + escapeHtml(field.key) + '" type="range" min="' + escapeHtml(String(field.min)) + '" max="' + escapeHtml(String(field.max)) + '" step="' + escapeHtml(String(field.step)) + '" value="' + escapeHtml(rangeAttr.indexOf('motion') !== -1 ? getMotionTuningText(field.key) : getAuraTuningText(field.key)) + '">',
            '<span ' + valueAttr + '="' + escapeHtml(field.key) + '" class="map-controls-range-value">' + escapeHtml(rangeAttr.indexOf('motion') !== -1 ? getMotionTuningText(field.key) : getAuraTuningText(field.key)) + '</span>',
            '<input ' + numberAttr + '="' + escapeHtml(field.key) + '" type="number" min="' + escapeHtml(String(field.min)) + '" max="' + escapeHtml(String(field.max)) + '" step="' + escapeHtml(String(field.step)) + '" value="' + escapeHtml(rangeAttr.indexOf('motion') !== -1 ? getMotionTuningText(field.key) : getAuraTuningText(field.key)) + '" class="map-controls-number-input">',
            '</label>'
        ].join('')).join('');
    }

    function buildAuraTuningMarkup(section) {
        const fields = AURA_TUNING_FIELDS.filter((field) => field.section === section);
        return buildRangeNumberRows(fields, 'data-map-aura-tuning', 'data-map-aura-tuning-number', 'data-map-aura-tuning-value');
    }

    function buildFxTuningMarkup(section) {
        const fields = FX_TUNING_FIELDS.filter((field) => field.section === section);
        return fields.map((field) => [
            '<label class="map-controls-range-row">',
            '<span>' + escapeHtml(field.label) + '</span>',
            '<input data-map-fx-tuning="' + escapeHtml(field.key) + '" type="range" min="' + escapeHtml(String(field.min)) + '" max="' + escapeHtml(String(field.max)) + '" step="' + escapeHtml(String(field.step)) + '" value="' + escapeHtml(getFxTuningText(field.key)) + '">',
            '<span data-map-fx-tuning-value="' + escapeHtml(field.key) + '" class="map-controls-range-value">' + escapeHtml(getFxTuningText(field.key)) + '</span>',
            '<input data-map-fx-tuning-number="' + escapeHtml(field.key) + '" type="number" min="' + escapeHtml(String(field.min)) + '" max="' + escapeHtml(String(field.max)) + '" step="' + escapeHtml(String(field.step)) + '" value="' + escapeHtml(getFxTuningText(field.key)) + '" class="map-controls-number-input">',
            '</label>'
        ].join('')).join('');
    }

    function buildMotionTuningMarkup() {
        return buildRangeNumberRows(MOTION_TUNING_FIELDS, 'data-map-motion-tuning', 'data-map-motion-tuning-number', 'data-map-motion-tuning-value');
    }

    function buildThemeTuningMarkup(section) {
        const fields = MAP_THEME_TUNING_FIELDS.filter((field) => field.section === section);
        return fields.map((field) => [
            '<label class="map-controls-range-row">',
            '<span>' + escapeHtml(field.label) + '</span>',
            '<input data-map-theme-tuning="' + escapeHtml(field.key) + '" type="range" min="' + escapeHtml(String(field.min)) + '" max="' + escapeHtml(String(field.max)) + '" step="' + escapeHtml(String(field.step)) + '" value="' + escapeHtml(getMapThemeTuningText(field.key)) + '">',
            '<span data-map-theme-tuning-value="' + escapeHtml(field.key) + '" class="map-controls-range-value">' + escapeHtml(getMapThemeTuningText(field.key)) + '</span>',
            '<input data-map-theme-tuning-number="' + escapeHtml(field.key) + '" type="number" min="' + escapeHtml(String(field.min)) + '" max="' + escapeHtml(String(field.max)) + '" step="' + escapeHtml(String(field.step)) + '" value="' + escapeHtml(getMapThemeTuningText(field.key)) + '" class="map-controls-number-input">',
            '</label>'
        ].join('')).join('');
    }

    function buildThemeColorMarkup(section) {
        const fields = MAP_THEME_COLOR_FIELDS.filter((field) => field.section === section);
        return fields.map((field) => [
            '<label class="map-controls-color-row" data-map-theme-row="' + escapeHtml(field.key) + '">',
            '<span>' + escapeHtml(field.label) + '</span>',
            '<input data-map-theme-color="' + escapeHtml(field.key) + '" type="color" value="' + escapeHtml(getMapThemeColorValue(field.key)) + '" class="map-controls-color-input">',
            '<span data-map-theme-color-value="' + escapeHtml(field.key) + '" class="map-controls-color-value">' + escapeHtml(getMapThemeColorValue(field.key).toUpperCase()) + '</span>',
            '</label>'
        ].join('')).join('');
    }

    function buildPresetButtons() {
        return Object.entries(AURA_PRESETS).map(([key, preset]) => {
            return '<button type="button" data-map-aura-preset="' + escapeHtml(key) + '" class="map-btn">' + escapeHtml(preset.label) + '</button>';
        }).join('');
    }

    function buildDepthButtons() {
        const labels = {
            root: 'Root Layer',
            layer1: 'Layer 1',
            layer2: 'Layer 2',
            layer3plus: 'Layer 3+'
        };
        return AURA_DEPTH_ORDER.map((key) => {
            return '<button type="button" data-map-aura-depth="' + escapeHtml(key) + '" class="map-btn">' + escapeHtml(labels[key] || key) + '</button>';
        }).join('');
    }

    function buildOverlayMarkup() {
        return [
            '<style>',
            '.map-controls-panel{display:none;flex-direction:column;gap:12px;align-items:stretch;align-self:stretch;box-sizing:border-box;width:min(100%,1080px);min-width:0;max-width:100%;max-height:min(calc(100vh - 112px),820px);min-height:0;padding:14px 16px;border:1px solid color-mix(in srgb, var(--map-theme-border-base) 72%, transparent);background:linear-gradient(180deg,color-mix(in srgb, var(--map-theme-panel-base) var(--map-theme-panel-fill), transparent) 0%,color-mix(in srgb, var(--map-theme-panel-strong-base) calc(var(--map-theme-panel-fill) - 8%), transparent) 100%);border-radius:16px;box-shadow:0 18px 34px rgba(0,0,0,0.28);backdrop-filter:blur(var(--map-theme-blur));overflow:hidden;color:var(--map-theme-text);}',
            '.map-controls-scroll{display:flex;flex:1 1 auto;min-height:0;flex-direction:column;gap:12px;overflow-y:auto;overflow-x:hidden;padding-right:8px;scrollbar-width:thin;scrollbar-color:color-mix(in srgb, var(--map-theme-accent) 62%, transparent) color-mix(in srgb, var(--map-theme-panel-base) 28%, transparent);}',
            '.map-controls-scroll::-webkit-scrollbar{width:10px;}',
            '.map-controls-scroll::-webkit-scrollbar-track{background:color-mix(in srgb, var(--map-theme-panel-base) 24%, transparent);border-radius:999px;}',
            '.map-controls-scroll::-webkit-scrollbar-thumb{background:linear-gradient(180deg,color-mix(in srgb, var(--map-theme-accent) 92%, white 8%) 0%,color-mix(in srgb, var(--map-theme-fx) 88%, var(--map-theme-panel-base) 12%) 100%);border-radius:999px;border:2px solid color-mix(in srgb, var(--map-theme-panel-strong-base) 82%, transparent);}',
            '.map-controls-scroll::-webkit-scrollbar-thumb:hover{background:linear-gradient(180deg,color-mix(in srgb, var(--map-theme-accent) 100%, white 0%) 0%,color-mix(in srgb, var(--map-theme-fx) 96%, white 4%) 100%);}',
            '.map-controls-scroll > *{min-width:0;}',
            '.map-controls-section{box-sizing:border-box;min-width:0;border:1px solid color-mix(in srgb, var(--map-theme-border-base) 58%, transparent);background:color-mix(in srgb, var(--map-theme-panel-base) 36%, transparent);border-radius:14px;padding:10px 12px;backdrop-filter:blur(calc(var(--map-theme-blur) * 0.7));}',
            '.map-controls-section summary{list-style:none;}',
            '.map-controls-section summary::-webkit-details-marker{display:none;}',
            '.map-controls-section[open] summary{margin-bottom:2px;}',
            '.map-controls-grid{display:grid;gap:14px 18px;align-items:start;min-width:0;}',
            '.map-controls-grid-2{grid-template-columns:repeat(auto-fit,minmax(260px,1fr));}',
            '.map-controls-grid-3{grid-template-columns:repeat(auto-fit,minmax(220px,1fr));}',
            '.map-controls-stack{display:flex;flex-direction:column;gap:8px;min-width:0;}',
            '.map-controls-chip-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap;min-width:0;}',
            '.map-controls-summary{font-size:0.74rem;color:var(--map-theme-text-muted);padding-left:4px;min-width:0;overflow-wrap:anywhere;}',
            '.map-controls-range-row{display:grid;grid-template-columns:minmax(92px,120px) minmax(0,1fr) 46px 64px;align-items:center;gap:8px;font-size:0.74rem;color:var(--map-theme-text);min-width:0;}',
            '.map-controls-range-row > span:first-child{min-width:0;overflow-wrap:anywhere;}',
            '.map-controls-range-row input[type="range"]{width:100%;min-width:0;}',
            '.map-controls-range-value{min-width:0;text-align:right;}',
            '.map-controls-number-input{width:64px;box-sizing:border-box;border:1px solid color-mix(in srgb, var(--map-theme-border-base) 72%, transparent);background:color-mix(in srgb, var(--map-theme-input-base) 82%, transparent);color:var(--map-theme-text);border-radius:8px;padding:6px 8px;outline:none;}',
            '.map-controls-color-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px 14px;align-items:start;}',
            '.map-controls-color-row{display:grid;grid-template-columns:minmax(94px,1fr) 48px minmax(82px,96px);align-items:center;gap:10px;font-size:0.74rem;color:var(--map-theme-text);min-width:0;padding:10px 12px;border-radius:12px;border:1px solid color-mix(in srgb, var(--map-theme-border-base) 52%, transparent);background:color-mix(in srgb, var(--map-theme-panel-base) 34%, transparent);box-shadow:inset 0 1px 0 color-mix(in srgb, white 5%, transparent);}',
            '.map-controls-color-row > span:first-child{min-width:0;overflow-wrap:anywhere;}',
            '.map-controls-color-row[data-map-theme-row="panelTint"],.map-controls-color-row[data-map-theme-row="panelEdge"]{border-color:color-mix(in srgb, var(--map-theme-border-base) 62%, transparent);background:linear-gradient(135deg,color-mix(in srgb, var(--map-theme-panel-base) 44%, transparent) 0%,color-mix(in srgb, var(--map-theme-panel-strong-base) 32%, transparent) 100%);}',
            '.map-controls-color-row[data-map-theme-row="mapAccent"]{border-color:color-mix(in srgb, var(--map-theme-accent) 58%, transparent);background:linear-gradient(135deg,color-mix(in srgb, var(--map-theme-accent) 18%, transparent) 0%,color-mix(in srgb, var(--map-theme-panel-base) 24%, transparent) 100%);box-shadow:inset 0 1px 0 color-mix(in srgb, white 6%, transparent),0 0 24px color-mix(in srgb, var(--map-theme-accent) 10%, transparent);}',
            '.map-controls-color-row[data-map-theme-row="auraAccent"]{border-color:color-mix(in srgb, var(--map-theme-aura) 66%, transparent);background:linear-gradient(135deg,color-mix(in srgb, var(--map-theme-aura) 22%, transparent) 0%,color-mix(in srgb, var(--map-theme-panel-base) 22%, transparent) 100%);box-shadow:inset 0 1px 0 color-mix(in srgb, white 7%, transparent),0 0 28px color-mix(in srgb, var(--map-theme-aura) 16%, transparent);}',
            '.map-controls-color-row[data-map-theme-row="fxAccent"]{border-color:color-mix(in srgb, var(--map-theme-fx) 66%, transparent);background:linear-gradient(135deg,color-mix(in srgb, var(--map-theme-fx) 22%, transparent) 0%,color-mix(in srgb, var(--map-theme-panel-base) 22%, transparent) 100%);box-shadow:inset 0 1px 0 color-mix(in srgb, white 7%, transparent),0 0 28px color-mix(in srgb, var(--map-theme-fx) 16%, transparent);}',
            '.map-controls-color-row[data-map-theme-row="titleColor"]{border-color:color-mix(in srgb, var(--map-theme-title) 60%, transparent);background:linear-gradient(135deg,color-mix(in srgb, var(--map-theme-title) 16%, transparent) 0%,color-mix(in srgb, var(--map-theme-panel-base) 22%, transparent) 100%);box-shadow:inset 0 1px 0 color-mix(in srgb, white 7%, transparent),0 0 24px color-mix(in srgb, var(--map-theme-title) 14%, transparent);}',
            '.map-controls-color-row[data-map-theme-row="dangerAccent"]{border-color:color-mix(in srgb, var(--map-theme-danger) 62%, transparent);background:linear-gradient(135deg,color-mix(in srgb, var(--map-theme-danger) 18%, transparent) 0%,color-mix(in srgb, var(--map-theme-panel-base) 22%, transparent) 100%);box-shadow:inset 0 1px 0 color-mix(in srgb, white 6%, transparent),0 0 24px color-mix(in srgb, var(--map-theme-danger) 14%, transparent);}',
            '.map-controls-color-row[data-map-theme-row="cardAuraFill"],.map-controls-color-row[data-map-theme-row="cardAuraDash"]{border-color:color-mix(in srgb, var(--map-theme-card-aura-dash) 62%, transparent);background:linear-gradient(135deg,color-mix(in srgb, var(--map-theme-card-aura-fill) 22%, transparent) 0%,color-mix(in srgb, var(--map-theme-panel-base) 22%, transparent) 100%);box-shadow:inset 0 1px 0 color-mix(in srgb, white 7%, transparent),0 0 30px color-mix(in srgb, var(--map-theme-card-aura-fill) 14%, transparent);}',
            '.map-controls-color-row[data-map-theme-row="workspaceAuraFill"],.map-controls-color-row[data-map-theme-row="workspaceAuraDash"]{border-color:color-mix(in srgb, var(--map-theme-workspace-aura-dash) 62%, transparent);background:linear-gradient(135deg,color-mix(in srgb, var(--map-theme-workspace-aura-fill) 22%, transparent) 0%,color-mix(in srgb, var(--map-theme-panel-base) 22%, transparent) 100%);box-shadow:inset 0 1px 0 color-mix(in srgb, white 7%, transparent),0 0 30px color-mix(in srgb, var(--map-theme-workspace-aura-fill) 14%, transparent);}',
            '.map-controls-color-row[data-map-theme-row="folderAuraFill"],.map-controls-color-row[data-map-theme-row="folderAuraDash"]{border-color:color-mix(in srgb, var(--map-theme-folder-aura-dash) 62%, transparent);background:linear-gradient(135deg,color-mix(in srgb, var(--map-theme-folder-aura-fill) 22%, transparent) 0%,color-mix(in srgb, var(--map-theme-panel-base) 22%, transparent) 100%);box-shadow:inset 0 1px 0 color-mix(in srgb, white 7%, transparent),0 0 30px color-mix(in srgb, var(--map-theme-folder-aura-fill) 14%, transparent);}',
            '.map-controls-color-input{width:48px;height:34px;padding:0;border:none;border-radius:10px;background:transparent;cursor:pointer;}',
            '.map-controls-color-input::-webkit-color-swatch-wrapper{padding:0;}',
            '.map-controls-color-input::-webkit-color-swatch{border:none;border-radius:10px;box-shadow:inset 0 0 0 1px color-mix(in srgb, var(--map-theme-border-base) 72%, transparent);}',
            '.map-controls-color-value{font-size:0.7rem;letter-spacing:0.04em;color:var(--map-theme-text-muted);text-transform:uppercase;}',
            '.map-theme-preview-row{display:flex;gap:8px;flex-wrap:wrap;align-items:center;padding-top:2px;}',
            '.map-theme-preview-chip{display:inline-flex;align-items:center;gap:8px;padding:7px 12px;border-radius:999px;border:1px solid color-mix(in srgb, var(--map-theme-border-base) 64%, transparent);background:color-mix(in srgb, var(--map-theme-button-base) calc(var(--map-theme-button-fill) + 10%), transparent);color:var(--map-theme-text);font-size:0.71rem;letter-spacing:0.03em;box-shadow:0 10px 22px rgba(0,0,0,0.16);}',
            '.map-theme-preview-chip::before{content:"";width:9px;height:9px;border-radius:999px;background:currentColor;box-shadow:0 0 16px currentColor;}',
            '.map-theme-preview-chip-map{color:var(--map-theme-accent);border-color:color-mix(in srgb, var(--map-theme-accent) 54%, transparent);background:color-mix(in srgb, var(--map-theme-accent) 14%, transparent);}',
            '.map-theme-preview-chip-aura{color:var(--map-theme-aura);border-color:color-mix(in srgb, var(--map-theme-aura) 56%, transparent);background:color-mix(in srgb, var(--map-theme-aura) 16%, transparent);}',
            '.map-theme-preview-chip-fx{color:var(--map-theme-fx);border-color:color-mix(in srgb, var(--map-theme-fx) 56%, transparent);background:color-mix(in srgb, var(--map-theme-fx) 16%, transparent);}',
            '.map-theme-preview-chip-title{color:var(--map-theme-title);border-color:color-mix(in srgb, var(--map-theme-title) 56%, transparent);background:color-mix(in srgb, var(--map-theme-title) 14%, transparent);}',
            '.map-theme-preview-chip-card-aura{color:var(--map-theme-card-aura-fill);border-color:color-mix(in srgb, var(--map-theme-card-aura-dash) 58%, transparent);background:color-mix(in srgb, var(--map-theme-card-aura-fill) 16%, transparent);}',
            '.map-theme-preview-chip-workspace-aura{color:var(--map-theme-workspace-aura-fill);border-color:color-mix(in srgb, var(--map-theme-workspace-aura-dash) 58%, transparent);background:color-mix(in srgb, var(--map-theme-workspace-aura-fill) 16%, transparent);}',
            '.map-theme-preview-chip-folder-aura{color:var(--map-theme-folder-aura-fill);border-color:color-mix(in srgb, var(--map-theme-folder-aura-dash) 58%, transparent);background:color-mix(in srgb, var(--map-theme-folder-aura-fill) 16%, transparent);}',
            '.map-shell-top{position:absolute;z-index:3;top:16px;left:20px;display:flex;flex-direction:column;gap:4px;max-width:min(48vw,680px);pointer-events:auto;}',
            '.map-shell-title{font-size:1.05rem;font-weight:700;letter-spacing:0.06em;color:var(--map-theme-title);text-shadow:0 0 18px color-mix(in srgb, var(--map-theme-accent) 20%, transparent);}',
            '.map-shell-subtitle{font-size:0.82rem;color:var(--map-theme-text-muted);}',
            '.map-shell-stats{font-size:0.78rem;color:color-mix(in srgb, var(--map-theme-text-muted) 82%, transparent);}',
            '.map-toolbar-stack{position:absolute;z-index:3;top:16px;right:20px;display:flex;flex-direction:column;gap:8px;align-items:flex-end;width:min(calc(100vw - 40px),980px);max-width:calc(100vw - 40px);pointer-events:auto;}',
            '.map-toolbar-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap;justify-content:flex-end;}',
            '.map-search-input{min-width:240px;border:1px solid color-mix(in srgb, var(--map-theme-border-base) 72%, transparent);background:color-mix(in srgb, var(--map-theme-input-base) 84%, transparent);color:var(--map-theme-text);border-radius:10px;padding:8px 12px;outline:none;backdrop-filter:blur(calc(var(--map-theme-blur) * 0.7));}',
            '.map-search-input::placeholder{color:var(--map-theme-text-muted);}',
            '.map-panel-header{display:flex;gap:8px;align-items:center;flex-wrap:wrap;justify-content:space-between;}',
            '.map-panel-title{font-size:0.86rem;font-weight:700;letter-spacing:0.04em;color:var(--map-theme-title);}',
            '.map-section-title{font-size:0.76rem;font-weight:700;color:var(--map-theme-text);}',
            '.map-section-copy{font-size:0.76rem;line-height:1.55;color:var(--map-theme-text-muted);}',
            '.map-btn-danger{border-color:color-mix(in srgb, var(--map-theme-danger) 62%, transparent) !important;background:color-mix(in srgb, var(--map-theme-danger) 18%, transparent) !important;color:var(--map-theme-text) !important;}',
            '.map-info-card{position:absolute;z-index:3;right:108px;bottom:20px;max-width:min(360px,calc(100vw - 200px));min-width:260px;border:1px solid color-mix(in srgb, var(--map-theme-border-base) 72%, transparent);background:color-mix(in srgb, var(--map-theme-panel-strong-base) 88%, transparent);border-radius:16px;padding:14px 16px;color:var(--map-theme-text);box-shadow:0 18px 40px rgba(0,0,0,0.35);backdrop-filter:blur(var(--map-theme-blur));pointer-events:auto;}',
            '.map-action-wheel{position:absolute;z-index:4;inset:0;display:none;pointer-events:none;}',
            '.map-action-wheel.is-visible{display:block;}',
            '.map-action-wheel-center{position:absolute;width:92px;height:92px;display:flex;align-items:center;justify-content:center;padding:12px;border-radius:999px;border:1px solid color-mix(in srgb, var(--map-theme-border-base) 76%, transparent);background:radial-gradient(circle at 32% 24%, color-mix(in srgb, var(--map-theme-panel-base) 94%, transparent), color-mix(in srgb, var(--map-theme-panel-strong-base) 94%, transparent));box-shadow:0 18px 40px rgba(0,0,0,0.34);transform:translate(-50%,-50%);text-align:center;color:var(--map-theme-title);font-size:0.72rem;font-weight:700;letter-spacing:0.03em;pointer-events:auto;}',
            '.map-action-wheel-item{position:absolute;display:inline-flex;align-items:center;justify-content:center;min-width:96px;max-width:132px;padding:9px 12px;border-radius:999px;border:1px solid color-mix(in srgb, var(--map-theme-border-base) 82%, transparent);background:color-mix(in srgb, var(--map-theme-button-base) calc(var(--map-theme-button-fill) + 12%), transparent);color:var(--map-theme-text);font-size:0.72rem;font-weight:600;line-height:1.2;box-shadow:0 14px 28px rgba(0,0,0,0.26);transform:translate(-50%,-50%);pointer-events:auto;cursor:pointer;text-align:center;backdrop-filter:blur(calc(var(--map-theme-blur) * 0.8));}',
            '.map-action-wheel-item.is-accent{border-color:color-mix(in srgb, var(--map-theme-accent) 52%, transparent);background:color-mix(in srgb, var(--map-theme-accent) 18%, transparent);}',
            '.map-action-wheel-item:hover{border-color:color-mix(in srgb, var(--map-theme-accent) 64%, transparent);background:color-mix(in srgb, var(--map-theme-accent) 22%, transparent);}',
            '@media (max-width: 1100px){.map-controls-range-row{grid-template-columns:minmax(82px,108px) minmax(0,1fr) 42px 58px;gap:6px;}.map-controls-number-input{width:58px;padding:6px;}}',
            '@media (max-width: 820px){.map-controls-grid-2,.map-controls-grid-3,.map-controls-color-grid{grid-template-columns:minmax(0,1fr);}.map-controls-panel{padding:12px;max-height:min(calc(100vh - 124px),820px);}.map-controls-summary{padding-left:0;}}',
            '</style>',
            '<div class="map-css-layer map-css-grid-layer"></div>',
            '<div class="map-css-layer map-css-tech-layer"></div>',
            '<div class="map-css-layer map-css-circuit-layer"></div>',
            '<div class="map-css-layer map-css-scanline-layer"></div>',
            '<div class="map-shell-top">',
            '<div data-map-title class="map-shell-title">NEURAL CORE :: CONSTELLATION MAP</div>',
            '<div data-map-scope class="map-shell-subtitle"></div>',
            '<div data-map-stats class="map-shell-stats"></div>',
            '</div>',
            '<div class="map-toolbar-stack">',
            '<div class="map-toolbar-actions">',
            '<input data-map-find type="search" placeholder="Find bookmark, card, folder..." class="map-search-input">',
            '<button type="button" data-map-toolbar="find" class="map-btn">Find</button>',
            '<button type="button" data-map-toolbar="zoom-out" class="map-btn">-</button>',
            '<button type="button" data-map-toolbar="zoom-in" class="map-btn">+</button>',
            '<button type="button" data-map-toolbar="fit" class="map-btn">Fit</button>',
            '<button type="button" data-map-toolbar="reset" class="map-btn">Reset</button>',
            '<button type="button" data-map-toolbar="labels" class="map-btn">Labels: Auto</button>',
            '<button type="button" data-map-toolbar="motion" class="map-btn">Motion: Web</button>',
            '<button type="button" data-map-toolbar="controls" class="map-btn">Control Center</button>',
            '<button type="button" data-map-toolbar="close" class="map-btn map-btn-danger">Close</button>',
            '</div>',
            '<div data-map-controls-panel class="map-controls-panel">',
            '<div class="map-panel-header">',
            '<div class="map-panel-title">Constellation Control Center</div>',
            '<div class="map-toolbar-actions">',
            '<button type="button" data-map-toolbar="aura-reset" class="map-btn">Reset Auras</button>',
            '<button type="button" data-map-toolbar="motion-reset" class="map-btn">Reset Motion</button>',
            '<button type="button" data-map-toolbar="controls-reset" class="map-btn">Reset All</button>',
            '</div>',
            '</div>',
            '<div class="map-controls-scroll">',
            '<details class="map-controls-section">',
            '<summary class="map-section-title" style="cursor:pointer;">Theme</summary>',
            '<div style="display:flex;flex-direction:column;gap:10px;padding-top:10px;">',
            '<div class="map-toolbar-actions" style="justify-content:space-between;">',
            '<div class="map-section-copy">With Follow Site Theme on, Constellation uses built-in dark and light aura palettes. Turn it off to use the custom map glass, aura, FX, and title colors below.</div>',
            '<div class="map-toolbar-actions">',
            '<button type="button" data-map-toolbar="theme-follow-site" class="map-btn">Follow Site Theme: ON</button>',
            '<button type="button" data-map-toolbar="open-site-theme" class="map-btn">Open Site Theme</button>',
            '<button type="button" data-map-toolbar="theme-reset" class="map-btn">Reset Theme</button>',
            '</div>',
            '</div>',
            '<div data-map-theme-summary class="map-controls-summary">' + escapeHtml(getMapThemeSummaryText()) + '</div>',
            '<div class="map-theme-preview-row">',
            '<div class="map-theme-preview-chip map-theme-preview-chip-map">Map Focus</div>',
            '<div class="map-theme-preview-chip map-theme-preview-chip-aura">Aura UI</div>',
            '<div class="map-theme-preview-chip map-theme-preview-chip-fx">FX Layer</div>',
            '<div class="map-theme-preview-chip map-theme-preview-chip-title">Title Glow</div>',
            '<div class="map-theme-preview-chip map-theme-preview-chip-card-aura">Card Aura</div>',
            '<div class="map-theme-preview-chip map-theme-preview-chip-workspace-aura">Tab Aura</div>',
            '<div class="map-theme-preview-chip map-theme-preview-chip-folder-aura">Folder Aura</div>',
            '</div>',
            '<div class="map-controls-grid map-controls-grid-3">',
            '<div class="map-controls-stack">',
            '<div class="map-section-title">Glass Shell</div>',
            '<div class="map-controls-color-grid">',
            buildThemeColorMarkup('shell'),
            '</div>',
            buildThemeTuningMarkup('shell'),
            '</div>',
            '<div class="map-controls-stack">',
            '<div class="map-section-title">Map-Only Accents</div>',
            '<div class="map-controls-color-grid">',
            buildThemeColorMarkup('map'),
            '</div>',
            '<div class="map-section-copy">Map accent drives buttons and focus lines. Aura accent colors field volumes. FX accent pushes the background layer palette. Title glow stays local to Constellation.</div>',
            '</div>',
            '<div class="map-controls-stack">',
            '<div class="map-section-title">Node Aura Palette</div>',
            '<div class="map-controls-color-grid">',
            buildThemeColorMarkup('auras'),
            '</div>',
            '<div class="map-section-copy">These colors directly control the fill and dashed boundary lines for card, tab, and folder auras so they stay distinct even when the shell follows the site theme.</div>',
            '</div>',
            '</div>',
            '</div>',
            '</details>',
            '<details class="map-controls-section">',
            '<summary class="map-section-title" style="cursor:pointer;">Background FX</summary>',
            '<div data-map-fx-panel style="display:flex;flex-direction:column;gap:10px;padding-top:10px;">',
            '<div class="map-toolbar-actions" style="justify-content:space-between;">',
            '<div class="map-section-copy">Interactive background engine, visual stack, and responsive tuning.</div>',
            '<button type="button" data-map-toolbar="fx-reset" class="map-btn">Reset FX</button>',
            '</div>',
            '<div class="fx-row">',
            '<div class="fx-label">Background Engine</div>',
            '<div class="fx-grid">',
            '<button class="fx-item-btn" data-fx-engine="none">None</button>',
            '<button class="fx-item-btn" data-fx-engine="solaris">Solaris</button>',
            '<button class="fx-item-btn" data-fx-engine="neural">Neural</button>',
            '<button class="fx-item-btn" data-fx-engine="waves">Waves</button>',
            '<button class="fx-item-btn" data-fx-engine="tokamak">Tokamak</button>',
            '<button class="fx-item-btn" data-fx-engine="memento">Memento</button>',
            '<button class="fx-item-btn" data-fx-engine="art">Art</button>',
            '<button class="fx-item-btn" data-fx-engine="raymarching">Raymarch</button>',
            '<button class="fx-item-btn" data-fx-engine="attraction">Attract</button>',
            '<button class="fx-item-btn" data-fx-engine="ascii">ASCII</button>',
            '<button class="fx-item-btn" data-fx-engine="blurred">Blurred</button>',
            '<button class="fx-item-btn" data-fx-engine="svgfilters">SVG Filter</button>',
            '<button class="fx-item-btn" data-fx-engine="particles">Particles</button>',
            '<button class="fx-item-btn" data-fx-engine="shaderedit">Shader Edit</button>',
            '<button class="fx-item-btn" data-fx-engine="dotwave">Dot Wave</button>',
            '<button class="fx-item-btn" data-fx-engine="cosmicsun">Cosmic Sun</button>',
            '<button class="fx-item-btn" data-fx-engine="auracursor">Aura Cursor</button>',
            '</div>',
            '</div>',
            '<div class="fx-row">',
            '<div class="fx-label">Visual Layers</div>',
            '<div class="fx-toggle-group">',
            '<div class="fx-toggle-chip" data-fx-toggle="grid">Grid</div>',
            '<div class="fx-toggle-chip" data-fx-toggle="scanline">Scanline</div>',
            '<div class="fx-toggle-chip" data-fx-toggle="tech">Tech</div>',
            '<div class="fx-toggle-chip" data-fx-toggle="circuit">Circuit</div>',
            '<div class="fx-toggle-chip" data-fx-toggle="neuralhud">Neural HUD</div>',
            '</div>',
            '</div>',
            '<div class="fx-row">',
            '<div class="fx-label">Interactive Controls</div>',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;">',
            '<button type="button" data-map-fx-flag="pointerReactive" class="map-btn">Pointer Reactive</button>',
            '<button type="button" data-map-fx-flag="parallaxEnabled" class="map-btn">Camera Parallax</button>',
            '</div>',
            '</div>',
            '<div class="map-controls-grid map-controls-grid-2">',
            '<div class="map-controls-stack">',
            '<div class="map-section-title">Engine Dynamics</div>',
            buildFxTuningMarkup('engine'),
            '</div>',
            '<div class="map-controls-stack">',
            '<div class="map-section-title">Layer Stack</div>',
            buildFxTuningMarkup('layers'),
            '<div class="map-section-title" style="padding-top:4px;">ASCII Layout</div>',
            buildFxTuningMarkup('ascii'),
            '</div>',
            '</div>',
            '</div>',
            '</details>',
            '<details class="map-controls-section">',
            '<summary class="map-section-title" style="cursor:pointer;">Auras</summary>',
            '<div style="display:flex;flex-direction:column;gap:10px;padding-top:10px;">',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;">',
            '<button type="button" data-map-aura-toggle="visuals" class="map-btn">Aura Volumes: ON</button>',
            '<button type="button" data-map-aura-toggle="effects" class="map-btn">Aura Forces: ON</button>',
            '<button type="button" data-map-aura-emitter="workspace" class="map-btn">Tab Auras</button>',
            '<button type="button" data-map-aura-emitter="category" class="map-btn">Card Auras</button>',
            '<button type="button" data-map-aura-emitter="folder" class="map-btn">Folder Auras</button>',
            '<span data-map-aura-preset-summary class="map-controls-summary">' + escapeHtml(getAuraPresetText()) + '</span>',
            '</div>',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;">',
            buildDepthButtons(),
            '</div>',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;">',
            buildPresetButtons(),
            '</div>',
            '<div class="map-controls-grid map-controls-grid-3">',
            '<div class="map-controls-stack">',
            '<div class="map-section-title">Tab Shape</div>',
            buildAuraTuningMarkup('workspace'),
            '</div>',
            '<div class="map-controls-stack">',
            '<div class="map-section-title">Card Shape</div>',
            buildAuraTuningMarkup('card'),
            '</div>',
            '<div class="map-controls-stack">',
            '<div class="map-section-title">Folder Shape</div>',
            buildAuraTuningMarkup('folder'),
            '</div>',
            '</div>',
            '</div>',
            '</details>',
            '<details open class="map-controls-section">',
            '<summary class="map-section-title" style="cursor:pointer;">Motion</summary>',
            '<div style="display:flex;flex-direction:column;gap:10px;padding-top:10px;">',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;">',
            '<button type="button" data-map-toolbar="motion" class="map-btn">Motion: Web</button>',
            '<button type="button" data-map-toolbar="stability" class="map-btn">Hold Main Nodes: ON</button>',
            '</div>',
            '<div style="display:flex;flex-direction:column;gap:8px;">',
            buildMotionTuningMarkup(),
            '</div>',
            '</div>',
            '</details>',
            '<details class="map-controls-section">',
            '<summary class="map-section-title" style="cursor:pointer;">Structure</summary>',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;padding-top:10px;">',
            '<button type="button" data-map-toolbar="chain-internal" class="map-btn">Same-Chain Forces: ON</button>',
            '<button type="button" data-map-toolbar="chain-external" class="map-btn">Cross-Chain Forces: ON</button>',
            '<button type="button" data-map-toolbar="chain-hierarchy" class="map-btn">Enforce Folder Layers: ON</button>',
            '<button type="button" data-map-toolbar="bookmark-hierarchy" class="map-btn">Keep Bookmark Lanes: ON</button>',
            '</div>',
            '</details>',
            '<details class="map-controls-section">',
            '<summary class="map-section-title" style="cursor:pointer;">Chain Editing</summary>',
            '<div style="display:flex;flex-direction:column;gap:10px;padding-top:10px;">',
            '<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;">',
            '<button type="button" data-map-toolbar="rewire-mode" class="map-btn">Chain Surgery: OFF</button>',
            '<button type="button" data-map-toolbar="rewire-cancel" class="map-btn">Cancel Move</button>',
            '</div>',
            '<div data-map-rewire-summary class="map-controls-summary">Drag or click a bookmark or folder to arm it, then drop or click a card or folder target. Use Detach to Parking when you want a floating orphan chain.</div>',
            '<div class="map-section-copy">',
            'Drag bookmark and folder nodes onto card or folder nodes to reattach them, or arm a node and click a valid target for fast reassignment. Right-click nodes for the action wheel, explicit parking detach, and create-and-attach flows. Use workspace or Unidex scope when you want to transfer chains across cards.',
            '</div>',
            '</div>',
            '</details>',
            '<details open class="map-controls-section">',
            '<summary class="map-section-title" style="cursor:pointer;">Static and Flow</summary>',
            '<div style="display:flex;flex-direction:column;gap:10px;padding-top:10px;">',
            '<div class="map-controls-chip-row" style="justify-content:flex-start;">',
            '<button type="button" data-map-toolbar="static-node" class="map-btn">Static Node</button>',
            '<button type="button" data-map-toolbar="static-chain" class="map-btn">Static Chain</button>',
            '<button type="button" data-map-toolbar="static-kind" class="map-btn">Static Type</button>',
            '<button type="button" data-map-toolbar="static-clear" class="map-btn">Clear Static</button>',
            '<div data-map-static-summary class="map-controls-summary">Static: none</div>',
            '</div>',
            '<div class="map-controls-chip-row" style="justify-content:flex-start;">',
            '<button type="button" data-map-static-kind="workspace" class="map-btn">Freeze ' + escapeHtml(getKindDisplayName('workspace')) + '</button>',
            '<button type="button" data-map-static-kind="category" class="map-btn">Freeze ' + escapeHtml(getKindDisplayName('category')) + '</button>',
            '<button type="button" data-map-static-kind="folder" class="map-btn">Freeze ' + escapeHtml(getKindDisplayName('folder')) + '</button>',
            '<button type="button" data-map-static-kind="link" class="map-btn">Freeze ' + escapeHtml(getKindDisplayName('link')) + '</button>',
            '</div>',
            '<div class="map-controls-chip-row" style="justify-content:flex-start;">',
            '<button type="button" data-map-toolbar="polarity-node" class="map-btn">Node: Inherit</button>',
            '<button type="button" data-map-toolbar="polarity-kind" class="map-btn">Type: Push</button>',
            '<button type="button" data-map-toolbar="polarity-clear" class="map-btn">Clear Flow</button>',
            '<div data-map-polarity-summary class="map-controls-summary">Flow: push default</div>',
            '</div>',
            '<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px 16px;align-items:start;">',
            '<label class="map-controls-range-row" style="grid-template-columns:42px minmax(112px,1fr) 50px 64px;">',
            '<span>Push</span>',
            '<input data-map-polarity-strength="repel" type="range" min="0" max="2.5" step="0.01" value="0.76" style="width:100%;">',
            '<span data-map-polarity-strength-value="repel" style="min-width:42px;text-align:right;">0.76</span>',
            '<input data-map-polarity-strength-number="repel" type="number" min="0" max="2.5" step="0.01" value="0.76" class="map-controls-number-input">',
            '</label>',
            '<label class="map-controls-range-row" style="grid-template-columns:42px minmax(112px,1fr) 50px 64px;">',
            '<span>Pull</span>',
            '<input data-map-polarity-strength="attract" type="range" min="0" max="2.5" step="0.01" value="0.62" style="width:100%;">',
            '<span data-map-polarity-strength-value="attract" style="min-width:42px;text-align:right;">0.62</span>',
            '<input data-map-polarity-strength-number="attract" type="number" min="0" max="2.5" step="0.01" value="0.62" class="map-controls-number-input">',
            '</label>',
            '</div>',
            '</div>',
            '</details>',
            '<details class="map-controls-section">',
            '<summary class="map-section-title" style="cursor:pointer;">Help</summary>',
            '<div class="map-section-copy" style="font-size:0.78rem;padding-top:10px;">',
            'Drag background to pan. Hold Space to force-pan through dense clusters. Drag nodes to reorganize. Mouse wheel zooms. Double-click a bookmark node to open it. Turn on Chain Surgery to drag bookmark and folder nodes onto cards or folders, or arm a node and click a valid target for fast reassignment. Right-click nodes for the action wheel, explicit parking detach, and create-and-attach flows. Use Auras to control volumes and chain shaping, Motion to tune physics, and Structure to clamp layer rules.',
            '</div>',
            '</details>',
            '</div>',
            '</div>',
            '</div>',
            '<canvas data-map-canvas style="position:absolute;z-index:1;inset:0;width:100%;height:100%;display:block;cursor:grab;"></canvas>',
            '<div data-map-action-wheel class="map-action-wheel"></div>',
            '<div data-map-info class="map-info-card"></div>'
        ].join('');
    }

    const toolbarMarkup = ns._toolbarMarkup = ns._toolbarMarkup || {};
    Object.assign(toolbarMarkup, {
        getInteractionTargetNode,
        buildMotionTuningMarkup,
        buildOverlayMarkup
    });
})(window.EveConstellationMap);
