// Auto-generated by server.py
window.googleCseConfig = {
    cx: '646ca4244f3524a8e',
    port: 3001,
    cloudFlareCompatible: true
};
console.log('Google CSE config loaded from server.py on port 3001');
