/* EveOS Manifest Styles */
window.EveModuleManifestParts = window.EveModuleManifestParts || {};
window.EveModuleManifestParts.styles = [
        // UI Modules
        'css/v1_folder.css?v=0.3.1',
        'js/modules/ui/sidebar.css?v=0.3.12',
        'js/modules/ui/tab-nav-history.css?v=0.4.7',
        'js/modules/ui/dashboard/dashboard.css?v=0.2.20',
        'js/modules/ui/dashboard/unidex-view.css?v=0.2.40',
        'js/modules/ui/dashboard/unidex-view.base.css?v=0.2.11',
        'js/modules/ui/dashboard/unidex-view.entries.css?v=0.2.17',
        'js/modules/ui/dashboard/unidex-view.theme.css?v=0.2.3',
        'js/modules/ui/dashboard/unidex-view.responsive.css?v=0.2.5',
        'js/modules/ui/dashboard/categories/focused-card.css?v=0.2.69',
        'js/modules/ui/dashboard/dock.css?v=0.2.6',
        'js/modules/ui/bulk-toolbar.css?v=0.2.7',
        'js/modules/ui/scratchpad.css?v=0.1.1',
        'js/modules/ui/context-menus/styles.css?v=0.2.41',
        'js/modules/ui/inline-prompt.css',
        'js/modules/features/scraper/ui/loading-indicator/loading-indicator.css?v=0.1.2',

        // Feature Modules
        'js/modules/features/widgets.css',
        'js/modules/features/bookmark-identifiers.css?v=0.2.3',
        'js/modules/features/search.css',
        'js/modules/features/header-controls/hc.css',
        'js/modules/features/search-advanced/sa.css?v=0.1.3',
        'js/modules/features/api-search/search-results.css?v=0.1.1',
        'js/modules/features/api-search/card-settings.css?v=0.1.8',
        'js/modules/features/sources/sources.css',
        'js/modules/features/library/library.css?v=0.2.26',
        'css/modules/constellation-map.css?v=0.1.3',

        // --- Scraper Feature Styles (Ported) ---
        'js/modules/features/scraper/core/styles/variables.css?v=1.0.1',
        'js/modules/features/scraper/core/styles/base.css?v=1.0.2',
        'js/modules/features/scraper/core/styles/dark-mode.css?v=1.0.1',
        'js/modules/features/scraper/ui/styles/shared-highlight.css?v=1.0.1',
        'js/modules/features/scraper/ui/result-display/result-display.css?v=1.0.2',
        'js/modules/features/scraper/ui/tab-manager/tab-manager.css?v=1.0.1',
        'js/modules/features/scraper/ui/popup-manager/popup-manager.css?v=1.0.1',
        'js/modules/features/scraper/ui/module-status/ui-module-status.css?v=1.0.1',
        'js/modules/features/scraper/ui/styles/layout-controls.css?v=1.0.1',
        'js/modules/features/scraper/ui/dropdown-handler/dropdown.css?v=1.0.1',
        'js/modules/features/scraper/ui/styles/app-layout.css?v=1.0.3',
        'js/modules/features/scraper/ui/styles/legacy-enhancements.css?v=1.0.1',
        'js/modules/features/scraper/ui/styles/inline-overrides.css?v=1.0.5',
        'js/modules/features/scraper/ui/styles/badges.css?v=1.0.0',
        'js/modules/features/scraper/ui/search-controls/toggle-switches.css?v=1.0.0',
        'js/modules/features/scraper/ui/styles/control-center.css?v=1.0.4',
        'js/modules/features/scraper/ui/styles/domain-manager.css?v=1.0.1',
        'js/modules/features/scraper/ui/styles/article-cards.css?v=1.0.0',
        'js/modules/features/scraper/ui/result-display/cached-results.css?v=1.0.0',
        'js/modules/features/scraper/ui/result-display/result-layouts.css?v=1.0.0',
        'js/modules/features/scraper/ui/result-display/result-card.css?v=1.0.1',
        'js/modules/features/scraper/ui/result-display/result-grid.css?v=1.0.1',
        'js/modules/features/scraper/ui/result-display/result-container.css?v=1.0.1',
        'js/modules/features/scraper/ui/styles/failsafe.css?v=1.0.0',
        'js/modules/features/scraper/ui/styles/fallback-forms.css?v=1.0.0',
        'js/modules/features/scraper/ui/styles/layout-overrides.css?v=1.0.1',
        'js/modules/features/scraper/discovery/styles/google-search-ui.css?v=1.0.0',
        'js/modules/features/scraper/discovery/styles/entry-list.css?v=1.0.0',
        'js/modules/features/scraper/discovery/styles/wikipedia-section.css?v=1.0.0',
        'js/modules/features/scraper/discovery/styles/fandom-search.css?v=1.0.1',
        'js/modules/features/scraper/discovery/styles/google-search-internal.css?v=1.0.0',
        'js/modules/features/scraper/discovery/styles/wiki-listing.css?v=1.0.0',
        'js/modules/features/scraper/discovery/system/discovery.css?v=1.0.2',
        'js/modules/features/scraper/discovery/styles/domain-entry.css?v=1.0.0',
        'js/modules/features/scraper/discovery/styles/google-search-scraper.css?v=1.0.4',
        'js/modules/features/scraper/discovery/styles/google-knowledge-panel.css?v=1.0.0',
        'js/modules/features/scraper/discovery/styles/empty-states.css?v=1.0.0',
        'js/modules/features/scraper/discovery/styles/google-search-errors.css?v=1.0.0',
        'js/modules/features/scraper/features/wiki-manager.css?v=1.0.7',
        'js/modules/features/scraper/features/search-manager.css?v=1.0.2',
        'js/modules/features/scraper/features/cache-visualization.css?v=1.0.0',
        'js/modules/features/scraper/search/google-cse/google-cse-embedded.css?v=1.0.5',
        'js/modules/features/scraper/search/google-cse/google-cse-layout.css?v=1.0.0',
        'js/modules/features/scraper/search/google-cse/google-cse-results.css?v=1.0.0',
        'js/modules/features/scraper/search/google-cse/google-cse-overrides.css?v=1.0.0',
        'js/modules/features/scraper/search/shared/search-forms.css?v=1.0.1',
        'js/modules/features/scraper/utils/styles/utility.css?v=1.0.1',

        // Modal Modules
        'js/modules/modals/modals.css?v=0.2.23',

        // Gemini Integration Styles
        'css/modules/gemini/main_css_files.css',
        'css/modules/gemini/audio_playback_ui/audio_player.css',
        'css/modules/gemini/base_styles_ui/body_styles.css',
        'css/modules/gemini/button_group_ui/button_group.css',
        'css/modules/gemini/canvas_ui/canvas_element.css',
        'css/modules/gemini/chat_log_ui/chat_log.css',
        'css/modules/gemini/chat_message_ui/chat_message.css',
        'css/modules/gemini/chat_popup_ui/chat_popup.css',
        'css/modules/gemini/gemini_link_surfaces.css?v=0.6.5',
        'css/modules/gemini/layout_ui/app_container.css',
        'css/modules/gemini/layout_ui/demo_content.css',
        'css/modules/gemini/layout_ui/large_screen_layout.css',
        'css/modules/gemini/mdl_components_ui/mdl_buttons.css',
        'css/modules/gemini/mdl_components_ui/mdl_layout_header.css',
        'css/modules/gemini/previous_history_ui/previous_history.css',
        'css/modules/gemini/text_input_ui/send_button.css',
        'css/modules/gemini/text_input_ui/text_input.css',
        'css/modules/gemini/theme_ui/theme_variables.css',
        'css/modules/gemini/video_player_ui/video_player.css',
        'css/modules/gemini/video_player_ui/video_section.css',
        'css/modules/gemini/voice_input_ui/voice_select.css',
        'css/modules/gemini/gemini_collapsible.css?v=0.1.5',
];
